<Project Sdk="Microsoft.NET.Sdk.Web">
  <Import Project="..\..\common.props" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Shopularity.Public</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <CopyLocalLockFileAssemblies>True</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="4.0.0" />
    <PackageReference Include="Serilog.Sinks.Async" Version="1.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.7" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Shopularity.Contracts/Shopularity.Contracts.csproj" />
    <PackageReference Include="Volo.CmsKit.Public.Web" Version="10.4.1" />
    <PackageReference Include="Volo.CmsKit.Public.HttpApi" Version="10.4.1" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.AutoMapper" Version="10.4.1" />
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" Version="10.4.1" />
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic" Version="10.4.1" />
    <PackageReference Include="Volo.Abp.Autofac" Version="10.4.1" />
    <PackageReference Include="Volo.Abp.AspNetCore.Serilog" Version="10.4.1" />
    <PackageReference Include="Volo.Abp.AspNetCore.SignalR" Version="10.4.1" />
    <PackageReference Include="Volo.Abp.Swashbuckle" Version="10.4.1" />
    <PackageReference Include="Volo.Abp.Http.Client" Version="10.4.1" />
    <PackageReference Include="Volo.Abp.Http.Client.IdentityModel.Web" Version="10.4.1" />
    <PackageReference Include="Volo.Abp.AspNetCore.Authentication.OpenIdConnect" Version="10.4.1" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Studio.Client.AspNetCore" Version="1.2.2" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Logs\**" />
    <Content Remove="Logs\**" />
    <EmbeddedResource Remove="Logs\**" />
    <None Remove="Logs\**" />
  </ItemGroup>

  <ItemGroup>
  <Content Include="Pages\**\*.js">
    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
  </Content>
  <Content Include="Pages\**\*.css">
    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
  </Content>
  </ItemGroup>
</Project>