volumes:
  shopularity_rabbitmq:
networks:
  shopularity:
    external: true

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12.7-management-alpine
    volumes:
      - shopularity_rabbitmq:/var/lib/rabbitmq
    networks:
      - shopularity
    ports:
      - "15672:15672"
      - "5672:5672"