<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\common.props" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Shopularity.Ordering</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MiniExcel" Version="1.41.1" />
    <PackageReference Include="Volo.Abp.AutoMapper" Version="10.4.1" />
    <PackageReference Include="Volo.Abp.Ddd.Application" Version="10.4.1" />
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" Version="10.4.1" />
    <ProjectReference Include="..\Shopularity.Ordering.Contracts\Shopularity.Ordering.Contracts.csproj" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore" Version="10.4.1" />
  </ItemGroup>
</Project>